name: CountryLoginMessage
main: com.brohoof.countryloginmessage.CountryLoginMessagePlugin
version: 1.7.3
description: Prints player's country on connect
author: xPaw
authors: [SweetieBelle]
softdepend: [GeoIPTools]
commands:
    CountryLoginMessage:
        description: Management command for CountryLoginMessage
        usage: /CountryLoginMessage <reload>
permissions:
    countryloginmessage.reload:
        description: Allows you to reload the config.
        default: false